spring: #띄어쓰기 없음
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop; # ./ Project root
      # OR jdbc-url: jdbc:h2:tcp://localhost:9092/./data/testdb
      username: sa
      password:

#  datasource: #띄어쓰기 2칸
#    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE #4칸
#  username: sa
#  password:
#  driver-class-name: org.h2.Driver

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace
# org.hibernate.type: trace #띄어쓰기 2칸
